Wig.destroy_all

wig_a = Wig.create!(name: "MADISON", size: "small", color: "black", hair_style: "smooth", hair_type: "natural", url:"https://res.cloudinary.com/dcjj6hxol/image/upload/v1668544598/development/soaa145-01_ei77gr.jpg", address: "16 Rue Moreau de Jones,Fort-de-france, Martinique")
wig_b = Wig.create!(name: "ELISE", size: "large", color: "black", hair_style: "wavy", hair_type: "natural", url:"https://res.cloudinary.com/dcjj6hxol/image/upload/v1668544550/development/soaa185-01_ugzm0k.jpg", address: "18 Rue Camille Sylvestre,Le Lamentin, Martinique")
wig_c = Wig.create!(name: "ANASTASIA", size: "medium", color: "brown", hair_style: "curly", hair_type: "natural", url:"https://res.cloudinary.com/dcjj6hxol/image/upload/v1668544509/development/soaa135-01_alglk1.jpg", address: "30 Rue Victor Hugo,Saint-Joseph, Martinique")
wig_d = Wig.create!(name: "CAROLINE", size: "large", color: "black", hair_style: "smooth", hair_type: "artificial", url:"https://res.cloudinary.com/dcjj6hxol/image/upload/v1668544598/development/soaa132-01_f8txfz.jpg", address: "28 Rue du Franc-jeu,Le Lamentin, Martinique")
wig_e = Wig.create!(name: "JANICE", size: "large", color: "brown", hair_style: "curly", hair_type: "natural", url:"https://res.cloudinary.com/dcjj6hxol/image/upload/v1668544509/development/soaa197-01_medlud.jpg", address: "4 Rue Martin Luther King,Fort-de-france, Martinique")
wig_f = Wig.create!(name: "IVY", size: "small", color: "brown", hair_style: "wavy", hair_type: "natural", url:"https://res.cloudinary.com/dcjj6hxol/image/upload/v1668544509/development/soaa138-01_xhnqhl.jpg", address: "35 Rue Gérard Nouvet,Le Robert, Martinique")
wig_g = Wig.create!(name: "KIM", size: "large", color: "black", hair_style: "wavy", hair_type: "artificiall", url:"https://res.cloudinary.com/dcjj6hxol/image/upload/v1668544548/development/soaa11-01_jkuvwx.jpg", address: "Avenue Frantz Fanon,Ducos, Martinique")
wig_h = Wig.create!(name: "LORETTA", size: "large", color: "black", hair_style: "smooth", hair_type: "natural", url:"https://res.cloudinary.com/dcjj6hxol/image/upload/v1668544548/development/soaa113-01_x8cfhs.jpg", address: "38 Rue Antoine Siger,Fort-de-france, Martinique")
wig_j = Wig.create!(name: "CHLOE", size: "medium", color: "brown", hair_style: "smooth", hair_type: "natural", url:"https://res.cloudinary.com/dcjj6hxol/image/upload/v1668544550/development/soaa193-01_osupvx.jpg", address: "Cité Rene Dantin,Trois-Ilets, Martinique")
wig_k = Wig.create!(name: "ESTELLE", size: "small", color: "brown", hair_style: "curly", hair_type: "artificial", url:"https://res.cloudinary.com/dcjj6hxol/image/upload/v1668544508/development/soaa153-01_wzq8zf.jpg", address: "Avenue Condorcet,Fort-de-france, Martinique")
wig_l = Wig.create!(name: "ELISA", size: "large", color: "black", hair_style: "curly", hair_type: "natural", url:"https://res.cloudinary.com/dcjj6hxol/image/upload/v1668544549/development/soaa142-01_uwn5qz.jpg", address: "Avenue Du Petit Florentin,Schoelcher, Martinique")